name: Run UI functional test

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - name: Install Selenium
      run: |
        pip3 install selenium
    - name: Install pytest
      run: |
        pipenv install pytest
    - name: Test with pytest
      run: |
        pipenv run python -m pytest
        
